### ISSUE TITLE
Documents not aligning properly 

### ISSUE THREAD

**Issue by nyambati** [andela-kndungu/document-ms-frontend#26]
The document Are not aligning properlt when the content is long

<img width="1550" alt="screen shot 2016-08-30 at 09 01 02" src="https://cloud.githubusercontent.com/assets/12892110/18081195/bccd8644-6e90-11e6-8848-65e7731833eb.png">

**Comment by kndungu** [comment]
This was resolved when solving #19 

Refer to this pull request #43
