### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by kevgathuku** [andela-kndungu/document-ms-frontend#29]
When trying to edit one of my docs to add some content, I get this error when the document has a lot of text in the body.
<img width="1280" alt="screen shot 2016-08-30 at 11 20 16 am" src="https://cloud.githubusercontent.com/assets/3721994/18081635/cc6ca2fc-6ea3-11e6-95ec-ea5e341b8b81.png">

**Comment by kndungu** [comment]
Unfortunately I am unable to reproduce the bug.

I have however come across this possible solution: http://stackoverflow.com/questions/19917401/node-js-express-request-entity-too-large

Please let me know if it resolves the issue.

**Comment by kevgathuku** [comment]
Yes that was an issue with the backend. Increasing the body parser limit fixes it.
